protected/models/Kp.php
<?php

/**
 * This is the model class for table "{{kp}}".
 *
 * The followings are the available columns in table '{{kp}}':
 * @property integer $id
 * @property string $nama
 * @property string $npm
 * @property integer $tahun
 * @property string $pembimbing
 * @property string $pembimbing_lapangan
 * @property string $judul
 * @property string $deskripsi
 * @property string $jurusan
 * @property string $lokasi_kp
 * @property string $lokasi
 */
class Kp extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @return Kp the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{kp}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nama, npm, tahun, pembimbing, pembimbing_lapangan, judul, deskripsi, jurusan, lokasi_kp, lokasi', 'required'),
			array('tahun', 'numerical', 'integerOnly'=>true),
			array('nama, pembimbing, pembimbing_lapangan, judul, jurusan, lokasi_kp, lokasi', 'length', 'max'=>128),
			array('npm', 'length', 'max'=>12),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, nama, npm, tahun, pembimbing, pembimbing_lapangan, judul, deskripsi, jurusan, lokasi_kp, lokasi', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}
	
	public function scopes()
    {
      return array(
        'word_only'=>array(
          'select'=>"*",
        ),
      );
    }

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'nama' => 'Nama',
			'npm' => 'NPM',
			'tahun' => 'Tahun',
			'pembimbing' => 'Pembimbing',
			'pembimbing_lapangan' => 'Pembimbing Lapangan',
			'judul' => 'Judul',
			'deskripsi' => 'Deskripsi',
			'jurusan' => 'Jurusan',
			'lokasi_kp' => 'Lokasi Kerja Praktek',
			'lokasi' => 'Lokasi',
		);
	}
	public function getUrl()
	{
		return Yii::app()->createUrl('kp/view', array(
			'id'=>$this->id,
			'judul'=>$this->judul,
		));
	}
	
//	public function similiar($tag,$id)
//	{
//		$sql="SELECT judul, id FROM tbl_kp WHERE tags LIKE '%$tag%' and id<>'$id'";
//		$dataProvider4=new CSqlDataProvider($sql,array(
//			'keyField' => 'id',
//			'pagination'=>array(
//				'pageSize'=>10,
//			),
//		));
//		return $dataProvider4;
//	}
	
	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('nama',$this->nama,true);
		$criteria->compare('npm',$this->npm,true);
		$criteria->compare('tahun',$this->tahun);
		$criteria->compare('pembimbing',$this->pembimbing,true);
		$criteria->compare('pembimbing_lapangan',$this->pembimbing_lapangan,true);
		$criteria->compare('judul',$this->judul,true);
		$criteria->compare('deskripsi',$this->deskripsi,true);
		$criteria->compare('jurusan',$this->jurusan,true);
		$criteria->compare('lokasi_kp',$this->lokasi_kp,true);
		$criteria->compare('lokasi',$this->lokasi,true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria'=>$criteria,
		));
	}
}
?>

protected/controllers/KpController.php
<?php

class KpController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','search'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array(),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('create','update','admin','delete'),
				'expression'=>'Yii::app()->user->isAdmin==1',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
//		$dataProvider2=Kp::model()->similiar($tag,$id);
		
		$this->render('view',array(
			'model'=>$this->loadModel($id),
//			'dataProvider2'=>$dataProvider2,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Kp;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kp']))
		{
			$model->attributes=$_POST['Kp'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Kp']))
		{
			$model->attributes=$_POST['Kp'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
	$ajax = Yii::app()->request->getParam("ajax");
		if($ajax == "")
		{
			$ajax = "off";
		}
		
		$dataProvider=new CActiveDataProvider('Kp');
		
		if($ajax == "off") {
			$this->render('index',array(
				'dataProvider'=>$dataProvider,
			));
		}
		else{
			$this->renderPartial('index',array(
				'dataProvider'=>$dataProvider,
			));
			
			Yii::app()->end();
		}
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Kp('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Kp']))
			$model->attributes=$_GET['Kp'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}
	public function actionSearch()
	{
		$model=new Kp('search');
		if(isset($_GET['Kp']))
			$model->attributes=$_GET['Kp'];
		$this->render('search',array(
			'model'=>$model,
		));
	}
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Kp::model()->findByPk((int)$id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='kp-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/kp/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'kp-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'nama'); ?>
		<?php echo $form->textField($model,'nama',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'nama'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'npm'); ?>
		<?php echo $form->textField($model,'npm',array('size'=>12,'maxlength'=>12)); ?>
		<?php echo $form->error($model,'npm'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'tahun'); ?>
		<?php echo $form->textField($model,'tahun'); ?>
		<?php echo $form->error($model,'tahun'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'pembimbing'); ?>
		<?php echo $form->textField($model,'pembimbing',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'pembimbing'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'pembimbing_lapangan'); ?>
		<?php echo $form->textField($model,'pembimbing_lapangan',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'pembimbing_lapangan'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'judul'); ?>
		<?php echo $form->textField($model,'judul',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'judul'); ?>
	</div>
	
	
	<div class="row">
		<?php echo $form->labelEx($model,'deskripsi'); ?>
		<?php $this->widget('application.extensions.cleditor.ECLEditor', array(
			'model'=>$model,
			'attribute'=>'deskripsi',
			'options'=>array(
				'width'=>'650',
				'height'=>250,
				'useCSS'=>true,
			),
			'value'=>$model->deskripsi,));
		?>
		<?php echo $form->error($model,'deskripsi'); ?>
	</div>
	
	<div class="row">
		<?php echo $form->labelEx($model,'jurusan'); ?>
		<?php echo $form->textField($model,'jurusan',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'jurusan'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'lokasi_kp'); ?>
		<?php echo $form->textField($model,'lokasi_kp',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'lokasi_kp'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'lokasi'); ?>
		<?php echo $form->textField($model,'lokasi',array('size'=>60,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'lokasi'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/kp/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'nama'); ?>
		<?php echo $form->textField($model,'nama',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'npm'); ?>
		<?php echo $form->textField($model,'npm',array('size'=>12,'maxlength'=>12)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tahun'); ?>
		<?php echo $form->textField($model,'tahun'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'pembimbing'); ?>
		<?php echo $form->textField($model,'pembimbing',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'pembimbing_lapangan'); ?>
		<?php echo $form->textField($model,'pembimbing_lapangan',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'judul'); ?>
		<?php echo $form->textField($model,'judul',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'deskripsi'); ?>
		<?php echo $form->textArea($model,'deskripsi',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'jurusan'); ?>
		<?php echo $form->textField($model,'jurusan',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'lokasi_kp'); ?>
		<?php echo $form->textField($model,'lokasi_kp',array('size'=>60,'maxlength'=>128)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/kp/_view.php
<div class="post">
	<div class="title">
		<?php echo CHtml::link(CHtml::encode($data->judul), $data->url); ?>
	</div>
	
	<div class="nav">
		<b>By:</b>
		<?php echo $data->nama,', ' ,$data->tahun;  ?>
	</div>
	
</div>

protected/views/kp/_viv.php
<div class="post">

	<div class="title">
		<?php echo CHtml::link(CHtml::encode($data->judul), $data->url); ?>
	</div>
	
	<div class="content">
		</br><b>Description</b></br></br>
		<?php
			$this->beginWidget('CMarkdown', array('purifyOutput'=>true));
			
			echo "<p align='justify'>",$data->deskripsi,"</p>";
			$this->endWidget();
		?>
	</div>
	
</div>

protected/views/kp/admin.php
<?php
$this->breadcrumbs=array(
	'Laporan Kerja Praktek'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Kp', 'url'=>array('index')),
	array('label'=>'Create Kp', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('kp-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage KP</h1>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'kp-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'nama',
		'npm',
		'tahun',
		'pembimbing',
		'pembimbing_lapangan',
		/*
		'judul',
		'deskripsi',
		'jurusan',
		'lokasi_kp',
		'lokasi',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/kp/create.php
<?php
$this->breadcrumbs=array(
	'Kps'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Kp', 'url'=>array('index')),
	array('label'=>'Manage Kp', 'url'=>array('admin')),
);
?>

<h1>Create Kp</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/kp/index.php
<?php
$this->breadcrumbs=array(
	'Kerja Praktek',
);

$this->menu=array(
	array('label'=>'Create Kp', 'url'=>array('create')),
	array('label'=>'Manage Kp', 'url'=>array('admin')),
);
?>

<h1>Kerja Praktek</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/kp/search.php
<?php
$this->breadcrumbs=array(
	'Laporan Kerja Praktek'=>array('index'),
	'Cari',
);

$this->menu=array(
	array('label'=>'List Kp', 'url'=>array('index')),
	array('label'=>'Create Kp', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('kp-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Cari Laporan Kerja Praktek</h1>


<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'kp-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		array(
				'name'=>'judul',
				'type'=>'raw',
				'value'=>'CHtml::link(CHtml::encode($data->judul), $data->url)'
			),
		'jurusan',
		/*
		
		'deskripsi',
		
		
		'lokasi',
		*/
		
	),
)); ?>

protected/views/kp/update.php
<?php
$this->breadcrumbs=array(
	'Kps'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Kp', 'url'=>array('index')),
	array('label'=>'Create Kp', 'url'=>array('create')),
	array('label'=>'View Kp', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Kp', 'url'=>array('admin')),
);
?>

<h1>Update Kp <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/kp/view.php
<?php
$this->breadcrumbs=array(
	'Laporan Kerja Praktek'=>array('index'),
	$model->nama,
);

$this->menu=array(
	array('label'=>'List Kp', 'url'=>array('index')),
	array('label'=>'Create Kp', 'url'=>array('create')),
	array('label'=>'Update Kp', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Kp', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Kp', 'url'=>array('admin')),
);
?>

<h1>Laporan Kerja Praktek</h1><br>

<?php $this->renderPartial('_viv', array(
	'data'=>$model,
)); ?>


<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'judul',
		'nama',
		'npm',
		'pembimbing',
		'pembimbing_lapangan',
		'jurusan',
		'tahun',
		'lokasi_kp',
		'lokasi',
	),
)); 
?>